### ISSUE TITLE
Rejestracja/logowanie

### ISSUE THREAD

**Issue by suscilowicz** [suscilowicz/BWP#1]
Proponuje skorzystac z gemu devise ktory generuje wszystkie funkcjonalnosci zwiazane z tematyka rejestracji uzytkownikow oraz logowania.

**Comment by psadowski** [comment]
Dobry pomysł!

**Comment by suscilowicz** [comment]
Ok, wiec zajme sie tym.

**Comment by suscilowicz** [comment]
Zrobione.

**Comment by suscilowicz** [comment]
Trzeba zajac sie wygladem formularzy rejestracji oraz widokami.

**Comment by psadowski** [comment]
Zajmę się tym w późniejszych fazach projektu.

**Comment by suscilowicz** [comment]
Podczas tworzenia raportow dodalem relacje miedzy uzytkownikiem a raportem.

**Comment by suscilowicz** [comment]
Trzeba to usunac. Zamykam issue.
