### ISSUE TITLE
Mapy

### ISSUE THREAD

**Issue by psadowski** [suscilowicz/BWP#2]
Z założeń naszego projektu wynika, że musimy użyć map. Poczytałem o tym i proponuję API od Google.
Załączam również tutek do api.

https://www.sitepoint.com/use-google-maps-rails/

**Comment by suscilowicz** [comment]
Mysle, ze to dobry pomysl.

**Comment by suscilowicz** [comment]
Uzywamy tych map, wiec zamykam.
